// The card for /terms, generated by the same code as the homepage's. A route
// that declares its own openGraph replaces the layout's wholesale, and the
// opengraph-image file convention only attaches to the segment it sits in, so
// without this file /terms carries an og:url and no image at all.
export { default, alt, size, contentType } from "../opengraph-image";
